name: ci

on:
    push:
        branches: ['**']
    pull_request:
        branches: ['**']

jobs:
lint:
    strategy:
        matrix:
            node-version: [16]
            os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - name: SSH Remote Commands
          uses: appleboy/ssh-action@v0.1.5

        - run: npm lint
